# ----------------------------------------------------
# request

# 请求头
CommonRequest request

# 相机 ID
string camera_id

# 可选项，等待新帧的超时时间，单位 ms；为 0 时使用服务端默认值
uint32 timeout_ms

---

# ----------------------------------------------------
# response

# 响应头
CommonResponse response

# JPEG 图片数据
JpegImage jpeg