# 此接口是播放全身动作接口

# 请求头
RequestHeader header

# 触发源 定义见 McTaskSource.msg
string source

# 资源类型
int32 type

# 自有模型
int32 MIMIC_QY = 1

# 灵创模型
int32 MIMIC_LC = 2

# 全身动作名称，若motion为空，加载model中resource; 反之，从本地加载执行资源。
string motion

# onnx 模型绝对路径
string model

# 资源绝对路径，比如轨迹参考
string resource

# 是否打断(给后面animation接口合并预留)
bool interrupt

# 操作类型
int32 operation

# 预先加载
int32 PRELOAD = 1

# 开始执行
int32 EXECUTION = 2

---

# 响应头
CommonTaskResponse response
