# 预设动作

int32 value

# 恢复默认姿态
int32 DEFAULT_POS = 0

# 右手挥手
int32 RIGHT_ARM_WAVE = 1001

# 右手握手
int32 RIGHT_ARM_HANDSHAKE = 1002

# 左手握手1.5m上对象
int32 RIGHT_ARM_HANDSHAKE_FOR_1D5METER = 1003

# 左手挥手
int32 LEFT_ARM_WAVE = 1011

# 左手握手
int32 LEFT_ARM_HANDSHAKE = 1012

# 左手握手1.5m上对象
int32 LEFT_ARM_HANDSHAKE_FOR_1D5METER = 1013

# 双手比心
int32 BOTH_HANDS_MAKE_HEART = 2001

# 双手摆动，表达喜悦
int32 BOTH_HANDS_ACTION_HAPPY = 2002

# 双手动作，说话动作
int32 BOTH_HANDS_ACTION_TALKING = 2003

# 说话动作1
int32 T1_TALK1 = 2004

# 说话动作2
int32 T1_TALK2 = 2005

# 说话动作3
int32 T1_TALK3 = 2006

# 说话动作4
int32 T1_TALK4 = 2007

# 说话动作5
int32 T1_TALK5 = 2008

# 说话动作6
int32 T1_TALK6 = 2009

# 拍照动作1
int32 PHOTO_POSE_1 = 2011

# 拍照动作2
int32 PHOTO_POSE_2 = 2012

# 拍照动作3
int32 PHOTO_POSE_3 = 2013

# 拍照动作4
int32 PHOTO_POSE_4 = 2014

# 三连拍姿势
int32 PHOTO_THREE_SHOT = 2020

# -----------------------------------------------------------------------------------
# Q 预置的上肢动作
# -----------------------------------------------------------------------------------

# 招手
int32 Q_BECKON = 3001

# 握手
int32 Q_SHAKE_HANDS = 3002

# 碰拳
int32 Q_BUMP_FISTS = 3003

# 挥手
int32 Q_WAVE_HAND = 3004

# 情绪动作 - 开心
int32 Q_SHOW_HAPPINESS = 3005

# 双手比心
int32 Q_MAKE_HEART = 3007

# 加油
int32 Q_CHEER_ON = 3008

# 伸懒腰
int32 Q_STRETCH = 3010

# 讲话动作A
int32 Q_SPEAK_A = 3012

# 讲话动作B
int32 Q_SPEAK_B = 3013

# 讲话动作C
int32 Q_SPEAK_C = 3014

# 拥抱
int32 Q_HUG = 3018

# 拒绝
int32 Q_REFUSE = 3021

# 跳舞动作A
int32 Q_DANCE_A = 3046

# 跳舞动作B
int32 Q_DANCE_B = 3047

# 跳舞动作C
int32 Q_DANCE_C = 3048
