# -----------------------------------------------------------------------------------
# 一块音频设备的信息
# -----------------------------------------------------------------------------------

# 设备索引号
int32 id # -1: auto mode

# 设备标志符
string device_addr # builtin_mic builtin_speaker

# 设备类型
string device_type # builtin bluetooth

# 设备名称
string device_name # snd_card_name bluetooth

# 是否处于选中状态
bool is_sel
