#!/usr/bin/env bash
# Deploy the exhibition demo app to the robot brain board.
# Official scp pattern (快速入门指南 §2.1.5): key per robot SN from after-sales.
#
# Usage:  bash deploy_to_robot.sh <robot-ip> [<robotSN>_soc0-key-dir]
#   e.g.: bash deploy_to_robot.sh 10.1.1.100 ./T1-XXXX_soc0
#
# What it does:
#   1. copies apps/ (demo_ui + conversation + seedance, pure python, no build)
#   2. copies exhibition/ (page + fallback videos) + a board-local ark-config.js
#   3. copies .env with 600 perms (secrets never logged)
#   4. installs pip deps (requirements-robot.txt)
set -euo pipefail

ROBOT_IP="${1:?usage: deploy_to_robot.sh <robot-ip> [key-dir]}"
KEY_DIR="${2:-}"
REMOTE="run@${ROBOT_IP}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"          # repo root (works on the PC side)
ENV_FILE="/mnt/d/Qiyuan T1 Robotics project/.env"      # secrets live OUTSIDE the repo

SSH=(ssh -o StrictHostKeyChecking=accept-new)
SCP=(scp)
if [ -n "${KEY_DIR}" ]; then
  SSH+=(-i "${KEY_DIR%/}/id_ed25519")
  SCP+=(-i "${KEY_DIR%/}/id_ed25519")
fi

echo "== deploying to ${REMOTE} =="
"${SSH[@]}" "${REMOTE}" "mkdir -p /home/user/qiyuan-demo"

echo "-- apps (pure python, no build on the robot)"
"${SCP[@]}" -r "${REPO_ROOT}/apps" "${REMOTE}:/home/user/qiyuan-demo/"

echo "-- exhibition page + assets"
"${SCP[@]}" -r "${REPO_ROOT}/exhibition" "${REMOTE}:/home/user/qiyuan-demo/"

echo "-- board-local ark-config.js (robotUrl = loopback on the board)"
python3 - "${ENV_FILE}" <<'PYEOF'
import sys
lines = open(sys.argv[1], encoding="utf-8").read().splitlines()
key = ""
for line in lines:
    if line.startswith("SEEDANCE_API_KEY="):
        key = line.partition("=")[2].strip()
        break
cfg = """// Board-local page config (generated by deploy_to_robot.sh)
window.ARK_CFG = {
  mode: 'direct',
  robotUrl: 'http://127.0.0.1:8766/demo/last',
  arkKey: '%s',
  arkModel: 'dreamina-seedance-2-0-fast-260128',
  arkBase: 'https://ark.ap-southeast.bytepluses.com/api/v3',
  fakeVideo: ''
};
""" % key
open("/tmp/ark-config-robot.js", "w", encoding="utf-8").write(cfg)
print("ark-config.js prepared")
PYEOF
"${SCP[@]}" /tmp/ark-config-robot.js "${REMOTE}:/home/user/qiyuan-demo/exhibition/exhibition/ark-config.js"
rm -f /tmp/ark-config-robot.js

echo "-- .env (secrets, chmod 600)"
"${SCP[@]}" "${ENV_FILE}" "${REMOTE}:/home/user/qiyuan-demo/.env"
"${SSH[@]}" "${REMOTE}" "chmod 600 /home/user/qiyuan-demo/.env"

echo "-- python deps"
"${SCP[@]}" "${REPO_ROOT}/scripts/requirements-robot.txt" "${REMOTE}:/home/user/qiyuan-demo/"
"${SSH[@]}" "${REMOTE}" "pip3 install -r /home/user/qiyuan-demo/requirements-robot.txt"

echo "-- start script"
"${SCP[@]}" "${REPO_ROOT}/scripts/run_demo_robot.sh" "${REMOTE}:/home/user/qiyuan-demo/"

echo
echo "DEPLOYED. Start the demo on the board with:"
echo "  ${SSH[*]} ${REMOTE} 'setsid bash /home/user/qiyuan-demo/run_demo_robot.sh > /tmp/qiyuan-demo.log 2>&1 < /dev/null &'"
echo "Then open on the page machine:  http://${ROBOT_IP}:8766/v2-aurora-flow.html"
