CommonRequest header

# play type, "emotion" or "file"
string type

# 播放的机器人内置表情id
int32[] emotion_ids

# 播放的视频地址
string[] file_paths

#  优先级，高优先级视频会打断低优先级视频。默认值0
int32 priority

# 整体配置的循环播放次数，大于0则播放具体次数。小于等于0，则表示循环播放 。默认值为1，表示播放一次
int32 loop_count

---

CommonResponse header